services:
  server1:
    build: .
    command: /root/server 1
    network_mode: host
  server2:
    build: .
    command: /root/server 2
    network_mode: host
  server3:
    build: .
    command: /root/server 3
    network_mode: host
  server4:
    build: .
    command: /root/server 4
    network_mode: host
